import "./globals.css";

export const metadata = {
  title: "Exclusive Game",
  Image: "/assets/webp/meta-img.webp",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>{children}</body>
    </html>
  );
}
